USE [UXFMUNI]
GO

/****** Object:  StoredProcedure [dbo].[Z_POTEST]    Script Date: 2020-11-25 08:39:40 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[Z_POTEST]
	@TYPE			NVARCHAR(30) = NULL,
	@ID				INT = NULL,
	@FTYPENAME		NVARCHAR(20) = NULL,
	@QTY			INT = NULL,
	@LOT			NVARCHAR(12) = NULL,
	@PTYPE			NVARCHAR(10) = NULL,
	@PNAME			NVARCHAR(10) = NULL,
	@TYPE_TEXT		NVARCHAR(500) = NULL,
	@DATE1			NVARCHAR(10) = NULL,
	@DATE2			NVARCHAR(10) = NULL,
	@MC_TEXT		NVARCHAR(1000) = NULL,
	@PT_TEXT		NVARCHAR(1000) = NULL,
	@SHIF_ID		INT = NULL,
	@SHIF_TYPE		NVARCHAR(100) = NULL,
	@CODE			nvarchar(10) = null

AS 

SET NOCOUNT ON 
	SET XACT_ABORT ON
	SET ANSI_NULLS ON
	SET ARITHABORT OFF 
	SET ANSI_WARNINGS OFF 


IF @TYPE ='GET_TITLE_INFO' GOTO GET_TITLE_INFO
ELSE IF @TYPE ='INSERT_TITLE' GOTO INSERT_TITLE
ELSE IF @TYPE = 'GET_LOT_TUAFTER' GOTO GET_LOT_TUAFTER
ELSE IF @TYPE = 'GET_SHEET_NAME' GOTO GET_SHEET_NAME
ELSE IF @TYPE = 'LOAD_LIST_TYPE' GOTO LOAD_LIST_TYPE
ELSE IF @TYPE = 'GET_PATTERN_REPORT' GOTO GET_PATTERN_REPORT
ELSE IF @TYPE = 'GET_PRODUCT' GOTO GET_PRODUCT


GET_TITLE_INFO:
		SET ANSI_WARNINGS ON
		SELECT * FROM UXFMUNI..VIEW_EMPY_EPZ WHERE STAUS = 1 and T_F_NAME like @FTYPENAME+'%'
		SET ANSI_WARNINGS OFF 
RETURN

INSERT_TITLE:
	--INSERT INTO UXFMUNI..ZZ_TESTTB(ID,TITLE,QTY)
	--VALUES (@ID,@FTYPENAME,@QTY)
RETURN

GET_LOT_TUAFTER:
	SELECT AF_LOT_NO,AF_PRO_ID,JAN_CODE,QTY_IN,NG_QTY FROM UXFMUNI..TU_AFTER_PRO_DATA WHERE AF_LOT_NO = @LOT
RETURN

GET_SHEET_NAME:
	SELECT '1' ID, 'S_NAME_01' S_NAME
	union
	SELECT '2' ID, 'S_NAME_02' S_NAME
	union
	SELECT '3' ID, 'S_NAME_03' S_NAME
	union
	SELECT '4' ID, 'S_NAME_04' S_NAME
	union
	SELECT '5' ID, 'S_NAME_05' S_NAME

	select ID,FABRIC_NAME,'Report one 1' AS TITLE from UXFMUNI..FABRIC_TYPE_NAME

	select ID,FABRIC_NAME,'Report two 2' AS TITLE from UXFMUNI..FABRIC_TYPE_NAME

	select ID,FABRIC_NAME,'Report two 3' AS TITLE from UXFMUNI..FABRIC_TYPE_NAME

	select ID,FABRIC_NAME,'Report two 4' AS TITLE from UXFMUNI..FABRIC_TYPE_NAME

	select ID,FABRIC_NAME,'Report two 5' AS TITLE from UXFMUNI..FABRIC_TYPE_NAME
RETURN

LOAD_LIST_TYPE:
	--table[0]
	SELECT DISTINCT PRODUCT_TYPE FROM UXNFDB..TEST_PATTERNT_LABEL WHERE PRODUCT_TYPE is not null
	--table[1] select product type
	SELECT RTRIM(TEST_PATTERN)PATTERN_ID, RTRIM(PATTERN_NA)PATTERN_NA, ('('+RTRIM(TEST_PATTERN)+') '+ RTRIM(PATTERN_NA)) As PATTERN_FULL
	FROM UXNFDB..TEST_PATTERNT_LABEL WHERE TEST_PATTERN <> 0

	--table[2] get machine no
	SELECT DISTINCT UNIP07 FROM UXNFDB..UNIPRDTB

	--table[3] select product type when edit change radioGroup
	IF @TYPE_TEXT = 'ALL'
	BEGIN
		SELECT RTRIM(TEST_PATTERN)PATTERN_ID, RTRIM(PATTERN_NA)PATTERN_NA 
			,('('+RTRIM(TEST_PATTERN)+') '+ RTRIM(PATTERN_NA)) As PATTERN_FULL
		FROM UXNFDB..TEST_PATTERNT_LABEL WHERE TEST_PATTERN <> 0
	END
	ELSE
	BEGIN
		--SELECT item as PROD_TYPE FROM UXFMUNI..Split_Function(@TYPE_TEXT,',')
		SELECT RTRIM(TEST_PATTERN)PATTERN_ID, RTRIM(PATTERN_NA)PATTERN_NA
			,('('+RTRIM(TEST_PATTERN)+') '+ RTRIM(PATTERN_NA)) As PATTERN_FULL
		FROM UXNFDB..TEST_PATTERNT_LABEL WHERE TEST_PATTERN <> 0 
		AND RTRIM(PRODUCT_TYPE) COLLATE DATABASE_DEFAULT IN (SELECT item FROM UXFMUNI..Split_Function(@TYPE_TEXT,','))
	END
RETURN

GET_PATTERN_REPORT:
	--table[0]
	SELECT DISTINCT RTRIM(PATTERN_NA)PATTERN_NA FROM UXNFDB..TEST_PATTERNT_LABEL WHERE TEST_PATTERN IN (SELECT item FROM UXFMUNI..Split_Function(@PT_TEXT,','))

	--table[1]
	declare @std nvarchar(6),@etd nvarchar(6)
	set @std = CONVERT(nvarchar(6),CONVERT(datetime,@DATE1),12)
	set @etd = CONVERT(nvarchar(6),CONVERT(datetime,@DATE2),12)

	CREATE TABLE #UNIPRDTEST(PATTERN_ID numeric(4,0),UNIP02 nvarchar(12),UNIP05 numeric(6,0),UNIP07 numeric(3,0),UNIP09 numeric(6,0),UNIP11 numeric(6,0),UNIP15 nvarchar(20)
		,UNIP16 nvarchar(10),UNIP17 nvarchar(6),UNIP37 numeric(4,0)
		--start test
		,MEAS_01_ST numeric(4,2),MEAS_02_ST numeric(4,2),MEAS_03_ST numeric(4,2),MEAS_04_ST numeric(4,2),MEAS_05_ST numeric(4,2),MEAS_06_ST numeric(4,2)
		,MEAS_07_ST nvarchar(30),MEAS_08_ST nvarchar(30),MEAS_09_ST nvarchar(30),MEAS_10_ST nvarchar(30),MEAS_11_ST nvarchar(30),MEAS_12_ST nvarchar(30)
		,MEAS_13_ST numeric(5,2),MEAS_14_ST numeric(5,2),MEAS_15_ST numeric(5,2),ST_TIME numeric(6,0)
		--finish test
		,MEAS_01_EN numeric(4,2),MEAS_02_EN numeric(4,2),MEAS_03_EN numeric(4,2),MEAS_04_EN numeric(4,2),MEAS_05_EN numeric(4,2),MEAS_06_EN numeric(4,2)
		,MEAS_07_EN nvarchar(30),MEAS_08_EN nvarchar(30),MEAS_09_EN nvarchar(30),MEAS_10_EN nvarchar(30),MEAS_11_EN nvarchar(30),MEAS_12_EN nvarchar(30)
		,MEAS_13_EN numeric(5,2),MEAS_14_EN numeric(5,2),MEAS_15_EN numeric(5,2),EN_TIME numeric(6,0)
		--other
		,UNIP61 nvarchar(30),UNIP62 nvarchar(30),UNIP63 nvarchar(10),UNIP64 numeric(4,0),UNIP65 numeric(5,1),UNIP66 numeric(4,0),UNIP67 numeric(5,1)
		,UNIP68 nvarchar(10),UNIP92 numeric(5,0),UNIPA9 numeric(4,0),UNIPAA numeric(4,0),UNIPAB numeric(4,0),UNIPAC numeric(4,0),UNIPAD numeric(4,0)
		,UNIPBJ nvarchar(2),UNIPBS numeric(4,0),REPORT_NO nvarchar(20),TEST_MC numeric(2,0))
	
	--get UNIPRDTB
	INSERT INTO #UNIPRDTEST
	SELECT (UNIPCD)PATTERN_ID
		,UNIP02, UNIP05, UNIP07, UNIP09, UNIP11, UNIP15, UNIP16, UNIP17, UNIP37
		--start test
		,(UNIP73)MEAS_01_ST, (UNIP74)MEAS_02_ST, (UNIP80)MEAS_03_ST, (UNIP81)MEAS_04_ST, (UNIP82)MEAS_05_ST, (UNIP83)MEAS_06_ST
		,(UNIPB7)MEAS_07_ST, (UNIPB7)MEAS_08_ST, (UNIPB7)MEAS_09_ST, (UNIPB8)MEAS_10_ST, (UNIPB8)MEAS_11_ST, (UNIPB8)MEAS_12_ST
		,(null)MEAS_13_ST, (null)MEAS_14_ST ,(null)MEAS_15_ST, (null)ST_TIME
		--finish test
		,(UNIP89)MEAS_01_EN, (UNIP90)MEAS_02_EN, (UNIP96)MEAS_03_EN, (UNIP97)MEAS_04_EN, (UNIP98)MEAS_05_EN, (UNIP99)MEAS_06_EN
		,(UNIPB9)MEAS_07_EN, (UNIPB9)MEAS_08_EN, (UNIPB9)MEAS_09_EN, (UNIPBA)MEAS_10_EN, (UNIPBA)MEAS_11_EN, (UNIPBA)MEAS_12_EN
		,(null)MEAS_13_EN, (null)MEAS_14_EN, (null)MEAS_15_EN, (null)EN_TIME
		--other
		,UNIP61, UNIP62, UNIP63, UNIP64, UNIP65, UNIP66, UNIP67, UNIP68, UNIP92, UNIPA9, UNIPAA, UNIPAB, UNIPAC, UNIPAD, UNIPBJ, UNIPBS
		,(NULL)REPORT_NO, (UNIPBB)TEST_MC
		FROM UXNFDB..UNIPRDTB
		WHERE UNIPA6 <> 1 AND UNIP05 >= DATEADD(YEAR,-2,GETDATE())--ย้อนหลัง2ปี
		AND UNIP05 >= @std AND UNIP05 <= @etd
		AND rtrim(UNIP02) not in (select rtrim(LOTNO) from UXNFDB..PRDTEST)
	--get PRDTEST
	INSERT INTO #UNIPRDTEST
	SELECT (TEST_PATTERN)PATTERN_ID
		,UNIP02, UNIP05, UNIP07, UNIP09, UNIP11, UNIP15, UNIP16, UNIP17, UNIP37
		--start test
		,MEAS_01_ST, MEAS_02_ST, MEAS_03_ST, MEAS_04_ST, MEAS_05_ST, MEAS_06_ST
		,MEAS_07_ST, MEAS_08_ST, MEAS_09_ST, MEAS_10_ST, MEAS_11_ST, MEAS_12_ST
		,MEAS_13_ST, MEAS_14_ST ,MEAS_15_ST, (null)ST_TIME
		--finish test
		,MEAS_01_EN, MEAS_02_EN, MEAS_03_EN, MEAS_04_EN, MEAS_05_EN, MEAS_06_EN
		,MEAS_07_EN, MEAS_08_EN, MEAS_09_EN, MEAS_10_EN, MEAS_11_EN, MEAS_12_EN
		,MEAS_13_EN, MEAS_14_EN, MEAS_15_EN, (null)EN_TIME
		--other
		,UNIP61, UNIP62, UNIP63, UNIP64, UNIP65, UNIP66, UNIP67, UNIP68, UNIP92, UNIPA9, UNIPAA, UNIPAB, UNIPAC, UNIPAD, UNIPBJ, UNIPBS
		,(NULL)REPORT_NO, ''TEST_MC
		FROM UXNFDB..UNIPRDTB
		LEFT JOIN UXNFDB..PRDTEST ON RTRIM(UNIP02) = LOTNO
		WHERE UNIPA6 <> 1 AND UNIP05 >= DATEADD(YEAR,-2,GETDATE())--ย้อนหลัง2ปี
		AND UNIP05 >= @std AND UNIP05 <= @etd
		AND rtrim(UNIP02) in (select rtrim(LOTNO) from UXNFDB..PRDTEST)

	IF @SHIF_ID = 0
		SET @SHIF_TYPE = 'A,B';
	IF @SHIF_ID = 1
		SET @SHIF_TYPE = 'A';
	IF @SHIF_ID = 2
		SET @SHIF_TYPE = 'B';
	declare @ROW int
	set @ROW = 1;
	--Create temp
	SELECT ROW_NUMBER() over (order by item)row_no,item into #patternList FROM UXFMUNI..Split_Function(@PT_TEXT,',')
	WHILE @ROW <= (SELECT COUNT(item) FROM #patternList)
	BEGIN
		SELECT
		A.UNIP07, A.UNIP02, A.UNIP15, A.UNIP16, A.UNIP17,/*A.UNIP09,A.UNIP11,*/A.UNIP37,A.UNIP05
		,CONVERT(varchar,RIGHT('00'+ CONVERT(varchar,Floor(A.UNIP09/3600)), 2))+':'+CONVERT(varchar,RIGHT('00'+ CONVERT(varchar,Floor((A.UNIP09%3600)/60)), 2)) AS UNIP09
		,CONVERT(varchar,RIGHT('00'+ CONVERT(varchar,Floor(A.UNIP11/3600)), 2))+':'+CONVERT(varchar,RIGHT('00'+ CONVERT(varchar,Floor((A.UNIP11%3600)/60)), 2)) AS UNIP11
		--PRDTEST Start test
		,A.MEAS_01_ST, A.MEAS_02_ST, A.MEAS_03_ST, A.MEAS_04_ST, A.MEAS_05_ST, A.MEAS_06_ST, A.MEAS_07_ST, A.MEAS_08_ST, A.MEAS_09_ST, A.MEAS_10_ST
		,A.MEAS_11_ST, A.MEAS_12_ST, A.MEAS_13_ST, A.MEAS_14_ST, A.MEAS_15_ST,'' As ST_TIME
		--PRDTEST Finish test
		,A.MEAS_01_EN, A.MEAS_02_EN, A.MEAS_03_EN, A.MEAS_04_EN, A.MEAS_05_EN, A.MEAS_06_EN, A.MEAS_07_EN, A.MEAS_08_EN, A.MEAS_09_EN, A.MEAS_10_EN
		,A.MEAS_11_EN, A.MEAS_12_EN, A.MEAS_13_EN, A.MEAS_14_EN, A.MEAS_15_EN,'' As EN_TIME
		--other
		,A.UNIPBJ, '' As REPORT_NO, A.TEST_MC, A.UNIP92, A.UNIP64, A.UNIP65, A.UNIP66, A.UNIP67, A.UNIPBS, A.UNIPA9, A.UNIPAA, A.UNIPAB, A.UNIPAC
		,A.UNIPAD, A.UNIP61, D.UNIM21, A.UNIP62, A.UNIP63, A.UNIP68

		FROM #UNIPRDTEST A
		LEFT OUTER JOIN UXNFDB..TEST_PATTERNT_LABEL C ON convert(varchar,A.PATTERN_ID) COLLATE DATABASE_DEFAULT = convert(varchar,C.TEST_PATTERN)
		LEFT OUTER JOIN UXNFDB..UNIMATERIALTB D ON RTRIM(A.UNIP61) COLLATE DATABASE_DEFAULT = D.UNIM01 
		WHERE A.UNIP07 IN (SELECT item FROM UXFMUNI..Split_Function(@MC_TEXT,','))
		--AND A.UNIP05 >= @std AND A.UNIP05 <= @etd
		AND A.PATTERN_ID IN (SELECT item FROM #patternList WHERE row_no = @ROW)
		AND SUBSTRING(A.UNIP02,10,1) COLLATE DATABASE_DEFAULT IN (SELECT item FROM UXFMUNI..Split_Function(@SHIF_TYPE,','))
		--set loop
		SET @ROW = @ROW+1
	END
	DROP TABLE #patternList
	DROP TABLE #UNIPRDTEST

RETURN

GET_PRODUCT:
	IF @CODE is null OR @CODE = ''
	begin
		select*from UXFMUNI..ZPO_PRODUCT order by P_CODE
	end

	else
	begin
		select*from UXFMUNI..ZPO_PRODUCT where P_CODE = @CODE
	end
RETURN
GO


